# Generated by Django 4.0.4 on 2022-06-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novelslist',
            fields=[
                ('novel_name', models.CharField(db_column='Novel_Name', max_length=200)),
                ('novel_id', models.AutoField(db_column='Novel_ID', primary_key=True, serialize=False)),
                ('novel_url', models.CharField(db_column='Novel_URL', max_length=200)),
                ('novel_numchapters', models.IntegerField(db_column='Novel_Numchapters')),
            ],
            options={
                'db_table': 'novelslist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Novelchapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_num', models.IntegerField(db_column='Chapter_Num')),
                ('chapter_text', models.TextField(db_column='Chapter_Text')),
                ('novel_id', models.ForeignKey(db_column='Novel_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='novels.novelslist')),
            ],
            options={
                'db_table': 'novelchapters',
                'managed': True,
            },
        ),
    ]
